# Generated by Django 6.0 on 2026-02-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title']},
        ),
    ]
