# Generated by Django 6.0 on 2026-02-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RunSQL(
        sql='ALTER TABLE blogapp_post ALTER COLUMN "time" TYPE timestamptz USING (CURRENT_DATE + "time") AT TIME ZONE \'UTC\';',
        reverse_sql='ALTER TABLE blogapp_post ALTER COLUMN "time" TYPE time WITHOUT TIME ZONE USING "time"::time;',
        state_operations=[
            migrations.AlterField(
                model_name='post',
                name='time',
                field=models.DateTimeField(),
            ),
        ],
    ),
    ]
