# Generated by Django 6.0 on 2026-02-09 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_comment_time_alter_post_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['time']},
        ),
    ]
