# Generated by Django 6.0 on 2026-02-09 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time']},
        ),
    ]
